---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - image: "dm848/srv-hello-world:v1"
          imagePullPolicy: Always
          name: hello-world
          ports:
            - containerPort: 8888
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: hello-world
  namespace: "default"
  labels:
    app: hello-world
spec:
  ports:
    - protocol: "TCP"
      port: 8888
      targetPort: 8888
  selector:
    app: hello-world
